approve_by_comment: true
approve_regex: '(?i)LGTM'
reject_regex: '(?i)NOT LGTM'
reset_on_push: true
signed_off_by:
  required: true
reviewers:
  required: 1
  members:
    - duglin
    - mhbauer
    - vaikas-google
    - bmelville
